version: "3"
services:
  game:
    image: ra3se/q3ra3-server:latest
    command: "/usr/games/quake3-server +set fs_game arena +exec server.cfg"
    ports:
      - "27960:27960/udp"
    restart: unless-stopped
    volumes:
      - ./pak0.pk3:/usr/share/games/quake3/baseq3/pak0.pk3
      - ./server.cfg:/usr/share/games/quake3/arena/server.cfg
      - ./arena.cfg:/usr/share/games/quake3/arena/arena.cfg
      - ./ra3.db:/var/games/quake3-server/.q3a/arena/ra3.db
